#!/usr/bin/env python3
"""
将 BlockSec 爬虫输出导入本地攻击知识库。

输入文件来自 scripts/crawl_blocksec_incidents.py，脚本会把每条交易转换为
KnowledgeBaseDB 样本，并保留项目方、chainID、txHash、事件原因、损失等结构化信息。
"""

from __future__ import annotations

import argparse
import json
import sys
import uuid
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
str_root = str(PROJECT_ROOT)
if str_root not in sys.path:
    sys.path.insert(0, str_root)

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

from database.models import KnowledgeBaseDB, SessionLocal  # noqa: E402


ROOT_CAUSE_CATEGORY_MAP = {
    "Access Control Issue": "access_control",
    "Accounting Error": "accounting_error",
    "Arbitrary Call": "arbitrary_call",
    "Arbitrary Calls": "arbitrary_call",
    "Business Logic Flaw": "business_logic",
    "Compromised Private Key": "private_key_compromise",
    "Double Accounting": "accounting_error",
    "Fee Mechanism Exploitation": "fee_mechanism",
    "Flawed Price Calculation": "price_manipulation",
    "Flawed Price Dependency": "price_manipulation",
    "Governance Attack": "governance_attack",
    "Integer Overflow": "integer_overflow",
    "Lack of Slippage Protection": "slippage_issue",
    "Lack Slippage Protection": "slippage_issue",
    "Misconfiguration": "misconfiguration",
    "Precision Loss": "precision_loss",
    "Reentrancy": "reentrancy",
    "Reward Calculation Error": "reward_calculation",
    "Storage Collision": "storage_collision",
    "Untrusted Input": "untrusted_input",
    "Unverified User Input": "unverified_input",
    "Vulnerable Price Dependency": "price_manipulation",
}

EXPLORER_TX_URLS = {
    1: "https://etherscan.io/tx/",
    10: "https://optimistic.etherscan.io/tx/",
    56: "https://bscscan.com/tx/",
    137: "https://polygonscan.com/tx/",
    250: "https://ftmscan.com/tx/",
    8453: "https://basescan.org/tx/",
    42161: "https://arbiscan.io/tx/",
    43114: "https://snowtrace.io/tx/",
    59144: "https://lineascan.build/tx/",
    81457: "https://blastscan.io/tx/",
    534352: "https://scrollscan.com/tx/",
}


@dataclass
class ImportStats:
    input_incidents: int = 0
    input_transactions: int = 0
    prepared: int = 0
    created: int = 0
    updated: int = 0
    skipped_existing: int = 0
    skipped_invalid: int = 0


def normalize_tx_hash(value: Any) -> str:
    tx_hash = str(value or "").strip().lower()
    return tx_hash if tx_hash.startswith("0x") and len(tx_hash) == 66 else ""


def normalize_chain_id(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    if not isinstance(payload, dict):
        raise ValueError("Input file must contain a JSON object generated by crawl_blocksec_incidents.py")
    return payload


def normalize_tags(values: list[Any]) -> list[str]:
    tags = {str(value).strip() for value in values if str(value).strip()}
    tags.add("blocksec")
    tags.add("security_incident")
    return sorted(tags)


def category_for_root_cause(root_cause: str) -> str:
    return ROOT_CAUSE_CATEGORY_MAP.get(root_cause, "security_incident")


def explorer_url(chain_id: int, tx_hash: str) -> str | None:
    base = EXPLORER_TX_URLS.get(chain_id)
    return f"{base}{tx_hash}" if base else None


def build_alert_data(incident: dict[str, Any], tx: dict[str, Any]) -> dict[str, Any]:
    return {
        "source": "blocksec",
        "blocksec_id": incident.get("blocksec_id"),
        "project": incident.get("project"),
        "project_logo": incident.get("project_logo"),
        "loss_usd": incident.get("loss_usd"),
        "loss_display": incident.get("loss_display"),
        "root_cause": incident.get("root_cause"),
        "event_time": incident.get("event_time"),
        "event_timestamp_ms": incident.get("event_timestamp_ms"),
        "media_url": incident.get("media_url"),
        "poc_url": incident.get("poc_url"),
        "rescued_usd": incident.get("rescued_usd"),
        "chain_id": tx.get("chain_id"),
        "chain_name": tx.get("chain_name"),
        "tx_hash": tx.get("tx_hash"),
        "tx_time": tx.get("tx_time"),
        "tx_timestamp_ms": tx.get("tx_timestamp_ms"),
        "attacker": tx.get("attacker") or None,
        "tx_label": tx.get("label") or "",
        "raw_incident": incident.get("raw") or {},
    }


def sample_from_incident_tx(incident: dict[str, Any], tx: dict[str, Any]) -> dict[str, Any] | None:
    tx_hash = normalize_tx_hash(tx.get("tx_hash"))
    chain_id = normalize_chain_id(tx.get("chain_id"))
    if not tx_hash or chain_id is None:
        return None

    root_cause = str(incident.get("root_cause") or "")
    project = str(incident.get("project") or "Unknown")
    chain_name = str(tx.get("chain_name") or chain_id)
    title = f"{project} - {root_cause}" if root_cause else f"{project} security incident"
    description = incident.get("description") or (
        f"{project} security incident on {chain_name}; root cause: {root_cause or 'unknown'}."
    )
    tags = normalize_tags(list(incident.get("tags") or []))
    labels = [tag for tag in tags if tag not in {"blocksec", "security_incident"}]

    return {
        "title": title,
        "description": description,
        "category": category_for_root_cause(root_cause),
        "tags": tags,
        "chain_id": chain_id,
        "tx_hash": tx_hash,
        "attacked_address": None,
        "exploiter_address": (str(tx.get("attacker") or "").strip() or None),
        "alert_data": build_alert_data(incident, {
            **tx,
            "tx_hash": tx_hash,
            "chain_id": chain_id,
            "attacker": str(tx.get("attacker") or "").strip() or None,
            "label": str(tx.get("label") or ""),
        }),
        "expected_severity": None,
        "expected_labels": labels,
        "expected_min_score": None,
        "source": "blocksec",
        "tx_explorer_url": explorer_url(chain_id, tx_hash),
    }


def build_samples(payload: dict[str, Any]) -> tuple[list[dict[str, Any]], ImportStats]:
    stats = ImportStats()
    samples: list[dict[str, Any]] = []
    seen_keys: set[tuple[int, str]] = set()
    incidents = payload.get("incidents") or []
    stats.input_incidents = len(incidents)

    for incident in incidents:
        if not isinstance(incident, dict):
            stats.skipped_invalid += 1
            continue
        transactions = incident.get("transactions") or []
        stats.input_transactions += len(transactions)
        for tx in transactions:
            if not isinstance(tx, dict):
                stats.skipped_invalid += 1
                continue
            sample = sample_from_incident_tx(incident, tx)
            if sample is None:
                stats.skipped_invalid += 1
                continue
            key = (sample["chain_id"], sample["tx_hash"])
            if key in seen_keys:
                continue
            seen_keys.add(key)
            samples.append(sample)

    stats.prepared = len(samples)
    return samples, stats


def find_existing(db, sample: dict[str, Any]) -> KnowledgeBaseDB | None:
    return (
        db.query(KnowledgeBaseDB)
        .filter(
            KnowledgeBaseDB.source == "blocksec",
            KnowledgeBaseDB.chain_id == sample["chain_id"],
            KnowledgeBaseDB.tx_hash == sample["tx_hash"],
        )
        .first()
    )


def apply_sample_to_row(row: KnowledgeBaseDB, sample: dict[str, Any]) -> None:
    row.title = sample["title"]
    row.description = sample["description"]
    row.category = sample["category"]
    row.tags = json.dumps(sample["tags"], ensure_ascii=False)
    row.chain_id = sample["chain_id"]
    row.tx_hash = sample["tx_hash"]
    row.attacked_address = sample["attacked_address"]
    row.exploiter_address = sample["exploiter_address"]
    row.alert_data = json.dumps(sample["alert_data"], ensure_ascii=False)
    row.expected_severity = sample["expected_severity"]
    row.expected_labels = json.dumps(sample["expected_labels"], ensure_ascii=False)
    row.expected_min_score = sample["expected_min_score"]
    row.source = sample["source"]
    row.tx_explorer_url = sample["tx_explorer_url"]
    row.updated_at = datetime.now()


def import_samples(samples: list[dict[str, Any]], stats: ImportStats, update_existing: bool) -> ImportStats:
    db = SessionLocal()
    try:
        for sample in samples:
            existing = find_existing(db, sample)
            if existing:
                if update_existing:
                    apply_sample_to_row(existing, sample)
                    stats.updated += 1
                else:
                    stats.skipped_existing += 1
                continue

            row = KnowledgeBaseDB(id=str(uuid.uuid4()))
            apply_sample_to_row(row, sample)
            db.add(row)
            stats.created += 1

        db.commit()
        return stats
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


def write_preview(samples: list[dict[str, Any]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps({"samples": samples}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="将 BlockSec 爬虫 JSON 导入本地攻击知识库。")
    parser.add_argument("--input", default="blocksec_incidents.json", help="crawl_blocksec_incidents.py 输出文件。")
    parser.add_argument("--apply", action="store_true", help="真正写入数据库；不传时只预览统计。")
    parser.add_argument("--update-existing", action="store_true", help="已存在相同 source+chain_id+tx_hash 时更新记录。")
    parser.add_argument("--preview-output", default="", help="可选：把转换后的导入样本写入预览 JSON。")
    parser.add_argument("--limit", type=int, default=None, help="最多导入/预览多少条交易样本。")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    payload = load_json(Path(args.input))
    samples, stats = build_samples(payload)
    if args.limit is not None:
        samples = samples[: max(0, args.limit)]
        stats.prepared = len(samples)

    if args.preview_output:
        write_preview(samples, Path(args.preview_output))

    if args.apply:
        stats = import_samples(samples, stats, update_existing=args.update_existing)
        mode = "imported"
    else:
        mode = "dry-run"

    print(
        f"BlockSec KB import {mode}: "
        f"incidents={stats.input_incidents}, "
        f"transactions={stats.input_transactions}, "
        f"prepared={stats.prepared}, "
        f"created={stats.created}, "
        f"updated={stats.updated}, "
        f"skipped_existing={stats.skipped_existing}, "
        f"skipped_invalid={stats.skipped_invalid}"
    )
    if not args.apply:
        print("No database changes were made. Re-run with --apply to write records.")


if __name__ == "__main__":
    main()
